MvcTest/Models/ErrorViewModel.cs
using System;

namespace MvcTest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcTest/Models/ReferralModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;
using MvcTest.Application.Entities;
namespace MvcTest.Models
{
    public class ReferralModel
    {
        [Required(ErrorMessage = "Forename is required.")]
        public string Forename { get; set; }

        [Required(ErrorMessage = "Surname is required.")]
        public string Surname { get; set; }

        [DisplayName("Date Of Birth")]
        [DataType(DataType.Date, ErrorMessage = "Please enter a valid date.")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime DateOfBirth { get; set; }


        [DisplayName("Date Of Referral")]
        [DisplayFormat (DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime DOR { get; set; }

        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [DisplayName("Email")]
        public string EmailAddress { get; set; }

        [DisplayName("Telephone")]
        public string ContactTelephoneNumber { get; set; }

        [DisplayName("Service Referred")]
        public string ServiceName { get; set; }
    }
}

MvcTest/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcTest.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcTest/Controllers/ReferralController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcTest.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using MvcTest.Application.Entities;
using MvcTest.Application.Persistence;
using Microsoft.Extensions.DependencyInjection;
using MvcTest.DataHelper;

namespace MvcTest.Controllers
{
    public class ReferralController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ReferralHelper referralHelper;

        public ReferralController(ILogger<HomeController> logger, ApplicationDbContext _dbContext)
        {
            _logger = logger;
            referralHelper = new ReferralHelper(_dbContext);
        }

        public IActionResult List(string searchItem = "")
        {
            var referralList = referralHelper.GetReferrals(searchItem);
            return View(referralList);
        }

        public IActionResult Create()
        {
            ViewData["ValidationError"] = "";
            return View();
        }
        [HttpPost]
        public IActionResult Create(ReferralModel referral)
        {
            if (!referralHelper.IsDataValid(referral, out string errorMessage))
            {
                ViewData["ValidationError"] =  errorMessage;
                return View(referral);
            }

            if (referralHelper.CreateReferral(referral) == true)
            {
                referralHelper.NotifyManager(referral);
            }   

            return View("ReferralAdded");
        }
    }
}

MvcTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the referral portal</h1>
    <p>Create your referrals quick and easy here.</p>

    <img src="/images/referrals.png" alt="referrals">
</div>

MvcTest/Views/Referral/Create.cshtml
@model MvcTest.Models.ReferralModel;

@{
    ViewData["Title"] = "Create Referral";
    List<SelectListItem> services = new List<SelectListItem>
        {
        new SelectListItem { Value = "Service One", Text = "Service One" },
        new SelectListItem { Value = "Service Two", Text = "Service Two" },

    };
}
<h1>Create Referral</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        @if (!string.IsNullOrEmpty(ViewData["ValidationError"].ToString())) 
        {
            <b>@ViewData["ValidationError"].ToString()</b>
        }

    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Forename" class="control-label"></label>
            <input asp-for="Forename" class="form-control" />
            <span asp-validation-for="Forename" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Surname" class="control-label"></label>
            <input asp-for="Surname" class="form-control" />
            <span asp-validation-for="Surname" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="DateOfBirth" class="control-label"></label>
            <input asp-for="DateOfBirth" class="form-control" />
            <span asp-validation-for="DateOfBirth" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ContactTelephoneNumber" class="control-label"></label>
            <input asp-for="ContactTelephoneNumber" class="form-control" />
            <span asp-validation-for="ContactTelephoneNumber" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="EmailAddress" class="control-label"></label>
            <input asp-for="EmailAddress" class="form-control" />
            <span asp-validation-for="EmailAddress" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ServiceName" class="control-label"></label>
            <br />
            <select asp-for="ServiceName" asp-items="services"></select>
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </form>
    </div>
</div>

MvcTest/Views/Referral/List.cshtml
@model IEnumerable<MvcTest.Models.ReferralModel>

@{
    ViewData["Title"] = "List Referrals";
}

<h1>List of Referrals</h1>
<label for="SearchItem">Search item:</label>
<input type="text" id="SearchItem" name="SearchItem">
<button type="button" name="btnSearch" id="btnSearch">Search</button>
<br>
<br>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Forename)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ServiceName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DOR)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactTelephoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailAddress)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Forename)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ServiceName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DOR)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactTelephoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmailAddress)
                </td>
            </tr>
        }
    </tbody>
</table>

<script language="JavaScript" type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        $("#btnSearch").click(function () {
            window.location.replace("/Referral/List?SearchItem=" + $("#SearchItem").val());
        });
    });
</script>

MvcTest/Views/Referral/ReferralAdded.cshtml
@model MvcTest.Models.ReferralModel;

@{
    ViewData["Title"] = "Referral Added";
}

<h6>
    Referral has been created successfully
</h6>

MvcTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Referral System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Referrals Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Referral" asp-action="Create">Create Referral</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Referral" asp-action="List">List Referrals</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MvcTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>